Repository harfbuzz/harfbuzz, pull requests merged in 2021-01, with the labels that each got.

#2820 [ci] Fix msys2 breakage
  .github/workflows/msys2-ci.yml
Labels: ci

#2819 [meson] Pin Cairo subproject 1.17.4
  subprojects/cairo.wrap
Labels: meson

#2801 [use] Move most joining scripts to USE
  src/hb-ot-shape-complex.hh
Labels: USE

#2824 [docs] Ignore hb-gobject headers
  docs/Makefile.am
  docs/harfbuzz-docs.xml
  docs/harfbuzz-sections.txt
  docs/meson.build
  src/hb-gobject-structs.h
Labels: documentation

#2831 [subet/COLR] Default initialize firstLayerIdx
  src/hb-ot-color-colr-table.hh
Labels: subset
